# Generated by Django 5.1 on 2026-02-14 10:46

import apps.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('unidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LocalFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('edificio', models.CharField(max_length=100, verbose_name='Edifício')),
                ('andar', models.CharField(blank=True, default='', max_length=20, verbose_name='Andar')),
                ('sala', models.CharField(blank=True, default='', max_length=50, verbose_name='Sala')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Local Físico',
                'verbose_name_plural': 'Locais Físicos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Contábil')),
                ('taxa_depreciacao_anual', models.DecimalField(decimal_places=2, help_text='Percentual ao ano. Ex: 20.00 = 20%', max_digits=5, verbose_name='Taxa Depreciação Anual (%)')),
                ('vida_util_padrao_meses', models.PositiveIntegerField(help_text='Vida útil padrão em meses. Ex: 60', verbose_name='Vida Útil Padrão (meses)')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='patrimonio.categoriacontabil', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Contábil',
                'verbose_name_plural': 'Categorias Contábeis',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero_tombamento', models.CharField(help_text='Número único e imutável da plaqueta/etiqueta.', max_length=30, unique=True, verbose_name='Nº Tombamento')),
                ('descricao_detalhada', models.TextField(verbose_name='Descrição Detalhada')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Aquisição (R$)')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Residual (R$)')),
                ('vida_util_meses', models.PositiveIntegerField(verbose_name='Vida Útil (meses)')),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível/Sucata')], default='NOVO', max_length=15, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_MANUTENCAO', 'Em Manutenção'), ('EM_PROCESSO_BAIXA', 'Em Processo de Baixa'), ('BAIXADO', 'Baixado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('depreciavel', models.BooleanField(default=True, help_text='Desmarque para terrenos ou itens sem depreciação.', verbose_name='Depreciável')),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=50, verbose_name='Nota Fiscal')),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ativos/', verbose_name='Foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='patrimonio.categoriacontabil', verbose_name='Categoria Contábil')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='patrimonio.centrocusto', verbose_name='Centro de Custo')),
                ('local_fisico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='patrimonio.localfisico', verbose_name='Local Físico')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.CharField(choices=[('LOCALIZADO', 'Localizado'), ('NAO_LOCALIZADO', 'Não Localizado')], default='NAO_LOCALIZADO', max_length=20, verbose_name='Presença')),
                ('estado_conservacao_encontrado', models.CharField(blank=True, choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível/Sucata')], default='', max_length=15, verbose_name='Estado Encontrado')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='patrimonio.ativo', verbose_name='Ativo')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='patrimonio.inventario', verbose_name='Inventário')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['ativo__numero_tombamento'],
                'unique_together': {('inventario', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='InventarioItemEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='inventarios/evidencias/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='patrimonio.inventarioitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Evidência de Inventário',
                'verbose_name_plural': 'Evidências de Inventário',
            },
        ),
        migrations.CreateModel(
            name='InventarioSobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.TextField(verbose_name='Descrição do Item')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventarios/sobras/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobras', to='patrimonio.inventario', verbose_name='Inventário')),
                ('local_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patrimonio.localfisico', verbose_name='Local Encontrado')),
            ],
            options={
                'verbose_name': 'Sobra de Inventário',
                'verbose_name_plural': 'Sobras de Inventário',
            },
        ),
        migrations.CreateModel(
            name='MotivoBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBSOLESCENCIA', 'Obsolescência'), ('FURTO', 'Furto/Roubo'), ('VENDA', 'Venda'), ('DOACAO', 'Doação'), ('SINISTRO', 'Sinistro'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo de Baixa')),
                ('data_baixa', models.DateField(verbose_name='Data da Baixa')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('valor_contabil_baixa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Contábil na Baixa (R$)')),
                ('documento_comprovante', models.FileField(blank=True, null=True, upload_to='baixas/', verbose_name='Documento Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baixa', to='patrimonio.ativo', verbose_name='Ativo')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
            ],
            options={
                'verbose_name': 'Motivo de Baixa',
                'verbose_name_plural': 'Motivos de Baixa',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=11, validators=[apps.core.validators.validar_telefone], verbose_name='Telefone')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_patrimonial', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_movimentacao', models.DateField(verbose_name='Data da Movimentação')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROVADA', 'Aprovada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=15, verbose_name='Status')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='patrimonio.ativo', verbose_name='Ativo')),
                ('centro_custo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.centrocusto', verbose_name='Centro de Custo Destino')),
                ('centro_custo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.centrocusto', verbose_name='Centro de Custo Origem')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.localfisico', verbose_name='Local de Destino')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.localfisico', verbose_name='Local de Origem')),
                ('responsavel_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.responsavel', verbose_name='Responsável Anterior')),
                ('responsavel_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patrimonio.responsavel', verbose_name='Novo Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='patrimonio.responsavel', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='patrimonio.responsavel', verbose_name='Responsável'),
        ),
        migrations.CreateModel(
            name='DepreciacaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes_referencia', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('cenario', models.CharField(choices=[('FISCAL', 'Fiscal'), ('SOCIETARIO', 'Societário/Gerencial')], default='FISCAL', max_length=15, verbose_name='Cenário')),
                ('valor_depreciado_mes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depreciação do Mês (R$)')),
                ('depreciacao_acumulada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depreciação Acumulada (R$)')),
                ('valor_contabil_atual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Contábil Atual (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciacoes', to='patrimonio.ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Registro de Depreciação',
                'verbose_name_plural': 'Registros de Depreciação',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('ativo', 'ano_referencia', 'mes_referencia', 'cenario')},
            },
        ),
    ]
