# Generated by Django 6.0.2 on 2026-02-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alter_inventario_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ativos/galeria/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, default='', help_text='Ex: Vista frontal, Número de série, Dano lateral', max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('AQUISICAO', 'Aquisição'), ('INVENTARIO', 'Inventário'), ('MANUTENCAO', 'Manutenção'), ('DANO', 'Dano'), ('OUTRO', 'Outro')], default='OUTRO', max_length=15, verbose_name='Tipo')),
                ('principal', models.BooleanField(default=False, help_text='Marque para exibir esta imagem em destaque na ficha do ativo.', verbose_name='Foto Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='patrimonio.ativo', verbose_name='Ativo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_patrimonio', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Imagem do Ativo',
                'verbose_name_plural': 'Imagens do Ativo',
                'ordering': ['-principal', '-criado_em'],
            },
        ),
    ]
