# Generated by Django 5.2.4 on 2026-02-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_galeria_imagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativo',
            options={
                'ordering': ['-criado_em'],
                'permissions': [('can_change_asset_status', 'Pode alterar status de ativo')],
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
