# Generated by Django 5.2.4 on 2026-02-15 00:10

from django.db import migrations


def _create_default_asset_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Ativo = apps.get_model('patrimonio', 'Ativo')

    ativo_ct = ContentType.objects.get_for_model(Ativo)

    permission_specs = {
        'can_set_asset_maintenance': 'Pode colocar ativo em manutenção',
        'can_return_asset_to_active': 'Pode retornar ativo para status ativo',
        'can_process_asset_disposal': 'Pode iniciar/processar baixa patrimonial',
        'can_change_asset_status': 'Pode alterar status de ativo',
    }

    perms_by_codename = {}
    for codename, name in permission_specs.items():
        perm, _ = Permission.objects.get_or_create(
            content_type=ativo_ct,
            codename=codename,
            defaults={'name': name},
        )
        if perm.name != name:
            perm.name = name
            perm.save(update_fields=['name'])
        perms_by_codename[codename] = perm

    operador_group, _ = Group.objects.get_or_create(name='Operador de Patrimônio')
    gestor_group, _ = Group.objects.get_or_create(name='Gestor de Patrimônio')

    operador_group.permissions.set(
        [
            perms_by_codename['can_set_asset_maintenance'],
            perms_by_codename['can_return_asset_to_active'],
        ]
    )
    gestor_group.permissions.set(
        [
            perms_by_codename['can_set_asset_maintenance'],
            perms_by_codename['can_return_asset_to_active'],
            perms_by_codename['can_process_asset_disposal'],
            perms_by_codename['can_change_asset_status'],
        ]
    )


def _remove_default_asset_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Operador de Patrimônio', 'Gestor de Patrimônio']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_alter_ativo_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativo',
            options={
                'ordering': ['-criado_em'],
                'permissions': [
                    ('can_change_asset_status', 'Pode alterar status de ativo'),
                    ('can_set_asset_maintenance', 'Pode colocar ativo em manutenção'),
                    ('can_return_asset_to_active', 'Pode retornar ativo para status ativo'),
                    ('can_process_asset_disposal', 'Pode iniciar/processar baixa patrimonial'),
                ],
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.RunPython(_create_default_asset_groups, _remove_default_asset_groups),
    ]
