# Generated by Django 5.2.4 on 2026-02-16 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_asset_role_groups_and_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoStatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_MANUTENCAO', 'Em Manutenção'), ('EM_PROCESSO_BAIXA', 'Em Processo de Baixa'), ('BAIXADO', 'Baixado')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_MANUTENCAO', 'Em Manutenção'), ('EM_PROCESSO_BAIXA', 'Em Processo de Baixa'), ('BAIXADO', 'Baixado')], max_length=20, verbose_name='Status Novo')),
                ('motivo', models.CharField(max_length=40, verbose_name='Motivo')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa detalhada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status_ativo', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='patrimonio.ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Ativo',
                'verbose_name_plural': 'Histórico de Status dos Ativos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
