# Generated by Django 6.0.2 on 2026-02-16 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_ativostatushistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_itens_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='inventarioitemevidencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_evidencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='inventarioitemevidencia',
            name='tipo',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('AVARIA', 'Avaria')], default='GERAL', max_length=20, verbose_name='Tipo'),
        ),
    ]
