# Generated by Django 5.1 on 2026-02-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insert_default_empresa'),
        ('patrimonio', '0007_inventarioitem_confirmado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='localfisico',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locais_fisicos', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to='core.empresa', verbose_name='Empresa'),
        ),
    ]
