# Generated by Django 5.1 on 2026-02-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insert_default_empresa'),
        ('patrimonio', '0008_ativo_empresa_centrocusto_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='core.empresa', verbose_name='Empresa'),
        ),
    ]
