# Generated by Django 5.1 on 2026-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0009_inventario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(blank=True, help_text='Deixe em branco para gerar automaticamente (DDMMYYHHMM)', max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
