# Generated by Django 5.1 on 2026-03-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0010_alter_inventario_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patrimonio.ativo')),
                ('tipo_imovel', models.CharField(choices=[('TERRENO', 'Terreno'), ('PREDIO', 'Prédio'), ('SALA', 'Sala Comercial'), ('GALPAO', 'Galpão'), ('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('LOTE', 'Lote'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo de Imóvel')),
                ('matricula_registro', models.CharField(blank=True, default='', help_text='Número da matrícula no cartório de registro de imóveis.', max_length=50, verbose_name='Matrícula/Registro')),
                ('cartorio', models.CharField(blank=True, default='', max_length=150, verbose_name='Cartório')),
                ('area_total_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área Total (m²)')),
                ('endereco_completo', models.TextField(blank=True, default='', verbose_name='Endereço Completo')),
                ('numero_iptu', models.CharField(blank=True, default='', max_length=30, verbose_name='Nº Inscrição IPTU')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
            bases=('patrimonio.ativo',),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patrimonio.ativo')),
                ('placa', models.CharField(help_text='Formato Mercosul ou antigo (ex: ABC1D23 ou ABC-1234)', max_length=10, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='RENAVAM')),
                ('chassi', models.CharField(blank=True, default='', max_length=25, verbose_name='Chassi')),
                ('marca_modelo', models.CharField(help_text='Ex: Fiat Uno, Toyota Hilux', max_length=100, verbose_name='Marca/Modelo')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('cor', models.CharField(blank=True, default='', max_length=30, verbose_name='Cor')),
                ('combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('FLEX', 'Flex'), ('DIESEL', 'Diesel'), ('ELETRICO', 'Elétrico'), ('HIBRIDO', 'Híbrido')], default='FLEX', max_length=10, verbose_name='Combustível')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
            bases=('patrimonio.ativo',),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('EQUIPAMENTO', 'Móvel/Equipamento'), ('IMOVEL', 'Imóvel'), ('VEICULO', 'Veículo')], db_index=True, default='EQUIPAMENTO', max_length=15, verbose_name='Tipo de Ativo'),
        ),
        migrations.CreateModel(
            name='SituacaoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('CEDIDO', 'Cedido'), ('EM_REFORMA', 'Em Reforma'), ('FECHADO', 'Fechado'), ('EM_USO_PROPRIO', 'Em Uso Próprio'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Situação')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes', to='patrimonio.imovel', verbose_name='Imóvel')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situacoes_imovel_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Situação do Imóvel',
                'verbose_name_plural': 'Situações dos Imóveis',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
    ]
