# Generated by Django 5.1 on 2026-02-23 13:15

from django.db import migrations

def create_default_empresa(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    if not Empresa.objects.filter(id=1).exists():
        Empresa.objects.create(
            id=1,
            nome_razao='Empresa Padrão (Fictícia)',
            nome_fantasia='Empresa Padrão',
            cnpj='00.000.000/0001-00',
            matriz=True,
            cidade='Indefinida',
            uf='SP',
            endereco='Indefinido',
            ativo=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_empresa, reverse_code=migrations.RunPython.noop),
    ]
